### ISSUE TITLE
BUG: Complex observables are not evaluable

### ISSUE THREAD

**Issue by hz-xiaxz** [lukas-weber/Carlo.jl#12]
Error occurs when evaluating complex observables.
```julia
ERROR: LoadError: MethodError: no method matching Carlo.Evaluable(::Int64, ::Int64, ::Int64, ::Vector{ComplexF64}, ::Vector{ComplexF64})

Closest candidates are:
  Carlo.Evaluable(::Int64, ::Int64, ::Int64, !Matched::Vector{T}, !Matched::Vector{T}) where T<:AbstractFloat
   @ Carlo ~/.julia/dev/Carlo/src/evaluable.jl:3
```
this is because of the definition of struct `Evaluable` 
```julia
struct Evaluable{T<:AbstractFloat}
    internal_bin_length::Int64
    rebin_length::Int64
    rebin_count::Int64

    mean::Vector{T}
    error::Vector{T}
end
```
where
```julia-repl
julia> ComplexF64 isa AbstractFloat
false
```

**Comment by hz-xiaxz** [comment]
How to perform jackknife reasonably on complex number datasets is a question. I will try to find some reference later, or we should find another suitable way to resample complex numbers.

**Comment by lukas-weber** [comment]
Ah, thanks forgot to test that feature!

-------- Original Message --------

**Comment by lukas-weber** [comment]
True, if you find a reference or a straightforward way to do it, you're welcome to open a pr.

I think a similar question appears already when computing the variance. But here I go with the definition of summing the real and imag variance just like the Julia functions do.

-------- Original Message --------
