### ISSUE TITLE
Support for parallel tempering?

### ISSUE THREAD

**Issue by rkr8** [lukas-weber/Carlo.jl#14]
Hi everyone,

Thanks for developing this nice software package! I was thinking about rewriting my not-so-organized MC code using this software package and was wondering if there is support for parallel tempering / replica-exchange MCMC sampling using MPI?

All the best,
Roman

**Comment by lukas-weber** [comment]
In the [old c++ version](https://github.com/lukas-weber/loadleveller) of this code, I did parallel tempering support, however it did not make it into the Julia version.

The way I would implement it nowadays is as a kind of adapter `ParallelTemperingMC{MC <: AbstractMC} <: AbstractMC` that itself acts like a normal `AbstractMC` (in [parallel-run mode](https://lukas.weber.science/Carlo.jl/dev/parallel_run_mode.html)) and performs parallel tempering on an underlying MC implementation.

This is on the to-do list for a future version of Carlo.jl. In case someone needs it for their research now, I am happy to provide support with implementing it yourself.

**Comment by rkr8** [comment]
Thanks for the quick response! That sounds promising. I would have to get more familiar with the software, but I’d be interested to have a look at the parallel tempering in the future. Thank you for the offer of support!

All the best,
Roman
