### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by rkr8** [lukas-weber/Carlo.jl#15]
Hi everyone,

I noticed that parallel tempering is now supported, which is fantastic! I have a few questions about some specific functionalities in the library that I’d love to clarify:

1. **Task Naming for Logging**: Is there a way to customize task names based on specific parameter combinations (e.g., `L`, `T` values)? Something like this: `(...) task_16_0.5 is done. Merging.`. Would you recommend overloading `Carlo.current_task_name(tm::TaskMaker)` to achieve this?

2. **Progress Logging During Execution**: Is it possible to log progress for each task while it’s running? I was thinking of inserting logging in `Carlo.measure!(mc::myMC, ctx::MCContext)`, but I’m not sure if that’s the best approach.

3. **Manual Binsize for Rebinning**: Is it possible to manually set the binsize during postprocessing? For instance, I would like to fit the autocorrelation time for each observable and then set the binsize based on the longest autocorrelation time. Additionally, is there an option to obtain directly resampled values in the merged results without averaging? This would help in further analyses, like calculating crossing points of the Binder cumulant for each sample to estimate error bars.

4. **Bootstrap Resampling in Postprocessing**: Finally, can the Bootstrap resampling method be used during postprocessing?

Thanks a lot for your help, and I appreciate all the work that has gone into this project!

**Comment by rkr8** [comment]
Hi, thank you very much for the quick and detailed response - this is very helpful! Given the workflow you suggested, I think the best approach in my case might indeed be to skip the merge step and perform the analysis directly on the HDF5 files in some script, to handle the autocorrelation & bootstrap resampling. Is there a flag or parameter I can set to bypass the built-in analysis and perform only the MC simulation itself?

Thanks again for your help!

**Comment by lukas-weber** [comment]
Sounds good. Unfortunately, that flag does not exist, but likely the cost of the analysis is negligible compared to the simulation time, so you can probably ignore it for now. On a side note, I just stumbled on [Bootstrap.jl](https://github.com/juliangehring/Bootstrap.jl) which might be useful.

If at the end you come up with something that may be useful to other people (either postprocessing logic or proposals for APIs that help working with HDF5 raw data), we can think about integrating it into Carlo somehow.

For now I’m opening some separate issues for the points you mentioned.

**Comment by rkr8** [comment]
Thank you very much, this sounds good!

**Comment by rkr8** [comment]
Hi!

Just a quick following:
For the direct postprocessing of the raw data in `myjob.data/$TASKNAME/run$N.meas.h5`, can I read parameters like the system size, temperature etc. directly from there? Or are they only stored in the results.json files?

Thanks a lot for your help!
