### ISSUE TITLE
[Bug] Overwritting `is_thermalized(ctx::MCContext)` is not allowed during Module precompilation

### ISSUE THREAD

**Issue by hz-xiaxz** [lukas-weber/Carlo.jl#21]
As iterated in the doc, I overwrite the `Carlo.is_thermalized` function for my own case, but got this error message:
```
WARNING: Method definition is_thermalized(Carlo.MCContext{RNG, Measure} where Measure where RNG<:Random.AbstractRNG) in module Carlo at /home/hzxiaxz/.julia/packages/Carlo/QLSQx/src/mc_context.jl:31 overwritten in module KagomeDSL at /home/hzxiaxz/.julia/dev/KagomeDSL.jl/src/MonteCarlo.jl:11.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
```
Don't have good ideas to solve it yet. Maybe we can make `is_thermalized` a `Bool` variable inside the `MCContext` struct? So we can simply change this variable outside. Also, in my case it is not quite enough to determine the thermalization from `ctx`, I may need variables from `MC` also. If we can do the change, it will be more flexible.

**Comment by lukas-weber** [comment]
Wait, I don't think the docs say you should overwrite `is_thermalized(::MCContext)`.

That function is just a shortcut that checks if ctx.sweeps is greater than the number of thermalization sweeps you set.

The only thing that influences is whether Carlos.measure! is called. You can always do your own thermalization check inside the Carlo.measure! function, where you have access to your internal state.

-------- Original Message --------
On 11/22/24 20:51, LeoXia wrote:
As iterated in the doc, I overwrite the Carlo.is_thermalized function for my own case, but got this error message:
WARNING: Method definition is_thermalized(Carlo.MCContext{RNG, Measure} where Measure where RNG<:Random.AbstractRNG) in module Carlo at /home/hzxiaxz/.julia/packages/Carlo/QLSQx/src/mc_context.jl:31 overwritten in module KagomeDSL at /home/hzxiaxz/.julia/dev/KagomeDSL.jl/src/MonteCarlo.jl:11. ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
Don't have good ideas to solve it yet. Maybe we can make is_thermalized a Bool variable inside the MCContext struct? So we can simply change this variable outside. Also, in my case it is not quite enough to determine the thermalization from ctx, I may need variables from MC also. If we can do the change, it will be more flexible.

**Comment by hz-xiaxz** [comment]
Yes, I think you are right. Apologize for the misunderstanding, this is not a bug. Thanks for your reply and time!
