### ISSUE TITLE
Direct sampling support

### ISSUE THREAD

**Issue by hz-xiaxz** [lukas-weber/Carlo.jl#9]
Hello! This is quite a nice package!
I'm a student working on a project using direct sampling method to simulated Fermion system, so it is different from the MCMC framework. But I'm still interested in the MPI frame and the job arrangement system this package. Will it be possible for me to take advantage of this package by e.g. set `thermalization=0` and use the MPI frame and autocorrelation caculation? I'll be appreciate if any guidance could be given. 
Or is there existing package that support parallel caculation of direct sampling problem?

**Comment by hz-xiaxz** [comment]
If you are interested, maybe we can work on a PR to add this feature

**Comment by lukas-weber** [comment]
Hi, apologies for the late reply!

In a still unpublished code, I am actually using Carlo as the framework to simulate Fermion systems using the [Auxiliary-field quantum Monte Carlo](https://www.cond-mat.de/events/correl13/manuscripts/zhang.pdf) method myself. That method is also not MCMC, but a one-sided projection/random walk.

Basically, Carlo gives you a way to process random numbers in parallel. If your method has no thermalization time, you can set `thermalization` to zero and it should work. If there are additional features you need, we can talk further :)

**Comment by hz-xiaxz** [comment]
Thanks, setting `thermalization` to zero works all well for my code!
